# Generated by Django 4.0.1 on 2022-05-21 14:48

import ckeditor.fields
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Al', 'Alamba'), ('Ak', 'Alaska'), ('Az', 'Arkansas'), ('Ca', 'Californiya'), ('Co', 'Colordo')], max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)], verbose_name='year')),
                ('condition', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', ckeditor.fields.RichTextField()),
                ('car_photo', models.ImageField(upload_to='photos/cars')),
                ('car_photo_1', models.ImageField(blank=True, upload_to='photos/cars')),
                ('car_photo_2', models.ImageField(blank=True, upload_to='photos/cars')),
                ('car_photo_3', models.ImageField(blank=True, upload_to='photos/cars')),
                ('car_photo_4', models.ImageField(blank=True, upload_to='photos/cars')),
                ('features', multiselectfield.db.fields.MultiSelectField(choices=[('Cruise Control', 'Cruise Control'), ('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Air Condition', 'Air Condition'), ('Alam System', 'Alam System'), ('Park Assist', 'Park Assist'), ('Power Steering', 'Power Steering'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto start/stop', 'Auto start/stop'), ('Wind Defender', 'Wind Defender'), ('Bluetooth Handset', 'Bluetooth Handset')], max_length=161)),
                ('body_style', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=100)),
                ('interior', models.CharField(max_length=100)),
                ('miles', models.IntegerField()),
                ('doors', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], max_length=100)),
                ('passengers', models.IntegerField()),
                ('vin_no', models.CharField(max_length=100)),
                ('milage', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=100)),
                ('no_of_owners', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
